INSERT INTO ROLE(ID, ROLE_NAME, DATE_CREATED, LAST_UPDATED) VALUES (1, 'ADMIN', NOW(), NOW());
INSERT INTO ROLE(ID, ROLE_NAME, DATE_CREATED, LAST_UPDATED) VALUES (2, 'USER', NOW(), NOW());

INSERT INTO USER(ID, USERNAME, ENCRYPTED_PASSWORD,ENABLED, DATE_CREATED, LAST_UPDATED)
  VALUES (1, 'admin', /*admin*/'$2a$12$mYNMU4.kxLtIW4QKzzrn4Os2cePD1emQuxUXBwxLl1XTB.qt3CeF6', TRUE, NOW(), NOW());

INSERT INTO USER(ID, USERNAME, ENCRYPTED_PASSWORD, ENABLED, DATE_CREATED, LAST_UPDATED)
  VALUES (2, 'user', /*user*/'$2a$12$Zu7p4noXQ5wptRESMpNdK.YQ8I9LCgjhKICAACHavWztEyuTIiUQ2', TRUE, NOW(), NOW());

INSERT INTO USERS_ROLES(USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES(USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USERS_ROLES(USER_ID, ROLE_ID) VALUES (2, 2);